DEFAULT_CATEGORIES = [
    "Vegetables & Fruits",
    "Fuel",
    "Food & Dining",
    "Online Shopping",
    "Metro Recharge",
    "Parking",
    "Transport & Cab",
    "Health & Pharmacy",
    "Subscriptions",
    "Utilities & Bills",
    "Clothing & Personal Care",
    "Entertainment & Outings",
    "Travel",
    "Transfers (P2P)",
    "Gym & Fitness",
    "Other",
]

CATEGORY_EMOJI = {
    "Vegetables & Fruits": "\U0001F966",
    "Fuel": "⛽",
    "Food & Dining": "\U0001F37D",
    "Online Shopping": "\U0001F6D2",
    "Metro Recharge": "\U0001F687",
    "Parking": "\U0001F17F",
    "Transport & Cab": "\U0001F697",
    "Health & Pharmacy": "\U0001F48A",
    "Subscriptions": "\U0001F4F1",
    "Utilities & Bills": "\U0001F4A1",
    "Clothing & Personal Care": "\U0001F457",
    "Entertainment & Outings": "\U0001F389",
    "Travel": "✈",
    "Transfers (P2P)": "\U0001F4B8",
    "Gym & Fitness": "\U0001F3CB",
    "Other": "❓",
}

# Pre-loaded keyword rules per FR-07 / bootstrap prompt
DEFAULT_KEYWORD_RULES = [
    ("bigbasket", "Vegetables & Fruits"),
    ("dunzo", "Vegetables & Fruits"),
    ("fresh", "Vegetables & Fruits"),
    ("sabzi", "Vegetables & Fruits"),
    ("vegetable", "Vegetables & Fruits"),
    ("kirana", "Vegetables & Fruits"),
    ("dmart", "Vegetables & Fruits"),
    ("more supermarket", "Vegetables & Fruits"),

    ("hpcl", "Fuel"),
    ("bpcl", "Fuel"),
    ("indian oil", "Fuel"),
    ("iocl", "Fuel"),
    ("hp petrol", "Fuel"),
    ("fuel", "Fuel"),
    ("petrol pump", "Fuel"),
    ("shell", "Fuel"),

    ("swiggy", "Food & Dining"),
    ("zomato", "Food & Dining"),
    ("cafe", "Food & Dining"),
    ("restaurant", "Food & Dining"),
    ("biryani", "Food & Dining"),
    ("pizza", "Food & Dining"),
    ("burger", "Food & Dining"),
    ("food", "Food & Dining"),
    ("darshini", "Food & Dining"),
    ("udupi", "Food & Dining"),

    ("amazon", "Online Shopping"),
    ("flipkart", "Online Shopping"),
    ("myntra", "Online Shopping"),
    ("meesho", "Online Shopping"),
    ("ajio", "Online Shopping"),
    ("nykaa", "Online Shopping"),
    ("snapdeal", "Online Shopping"),
    ("tata cliq", "Online Shopping"),

    ("namma metro", "Metro Recharge"),
    ("bmtc", "Metro Recharge"),
    ("ncmc", "Metro Recharge"),
    ("metro recharge", "Metro Recharge"),
    ("bangalore metro", "Metro Recharge"),
    ("nmmc", "Metro Recharge"),

    ("parking", "Parking"),
    ("parksmith", "Parking"),
    ("easypark", "Parking"),
    ("myfastag", "Parking"),
    ("fastag", "Parking"),
    ("park", "Parking"),

    ("ola", "Transport & Cab"),
    ("uber", "Transport & Cab"),
    ("rapido", "Transport & Cab"),
    ("cab", "Transport & Cab"),
    ("auto", "Transport & Cab"),
    ("taxi", "Transport & Cab"),
    ("ride", "Transport & Cab"),

    ("apollo", "Health & Pharmacy"),
    ("netmeds", "Health & Pharmacy"),
    ("1mg", "Health & Pharmacy"),
    ("medical", "Health & Pharmacy"),
    ("pharmacy", "Health & Pharmacy"),
    ("doctor", "Health & Pharmacy"),
    ("hospital", "Health & Pharmacy"),
    ("clinic", "Health & Pharmacy"),

    ("netflix", "Subscriptions"),
    ("spotify", "Subscriptions"),
    ("youtube", "Subscriptions"),
    ("hotstar", "Subscriptions"),
    ("jio", "Subscriptions"),
    ("airtel recharge", "Subscriptions"),
    ("prime", "Subscriptions"),
    ("subscription", "Subscriptions"),

    ("bescom", "Utilities & Bills"),
    ("electricity", "Utilities & Bills"),
    ("water", "Utilities & Bills"),
    ("gas", "Utilities & Bills"),
    ("indane", "Utilities & Bills"),
    ("broadband", "Utilities & Bills"),
    ("act fibernet", "Utilities & Bills"),
    ("tata sky", "Utilities & Bills"),

    ("gym", "Gym & Fitness"),
    ("fitness", "Gym & Fitness"),
    ("cult.fit", "Gym & Fitness"),
    ("cult fit", "Gym & Fitness"),
    ("protein", "Gym & Fitness"),
    ("supplement", "Gym & Fitness"),
    ("gold's gym", "Gym & Fitness"),

    ("irctc", "Travel"),
    ("makemytrip", "Travel"),
    ("goibibo", "Travel"),
    ("indigo", "Travel"),
    ("air india", "Travel"),
    ("hotel", "Travel"),
    ("oyo", "Travel"),
    ("cleartrip", "Travel"),

    ("bookmyshow", "Entertainment & Outings"),
    ("inox", "Entertainment & Outings"),
    ("pvr", "Entertainment & Outings"),
    ("event", "Entertainment & Outings"),
    ("concert", "Entertainment & Outings"),
    ("carnival", "Entertainment & Outings"),
]
